### ISSUE TITLE
Fix propagation of tracing span through async operation

### ISSUE THREAD

**Issue by elgris** [zalando-zmon/zmon-data-service#88]
**As a** developer
**I want to**  see that tracing span that belongs to outgoing request (executed asynchronously) and tracing span coming with incoming request (which triggers outgoing request) belong to the same trace
**So that** I get complete tracing picture

## Explanation
I'm going to explain it with a single example:

`data-service` receives requests with `DataServiceController#putData` handle. There it starts new span (probably belonging to some trace if request contains tracing information). Then it calls:
 `de.zalando.zmon.dataservice.data.WorkResultWriter#write` (implemented by `de.zalando.zmon.dataservice.data.ApplicationMetricsWriter#write`) and then -
 `de.zalando.zmon.dataservice.data.AppMetricsClient#receiveData`.
`AppMetricsClient#receiveData` sends outgoing requests to [metric-cache](https://github.com/zalando-zmon/zmon-metric-cache) **asynchronously** with `org.apache.http.client.fluent.Async`. The problem is that span context is not propagated to async processor. Therefore outgoing request triggers generation of new tracing span which is not bound to original trace, it becomes separate.

We have not solved this problem for async operations (yet). For `data-service` the problem is valid everywhere async processing is used. Also it's relevant to `zmon-controller` and other Java components that execute async operations without trace propagation.

**Comment by rajatparida86** [comment]
Closing as it is already done
